"""create fihirana table

Revision ID: 447058c615dd
Revises: e629032f0dc2
Create Date: 2025-11-18 23:02:29.011708

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '447058c615dd'
down_revision = 'e629032f0dc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fihirana',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('paroles', sa.Text(), nullable=False),
    sa.Column('collection', sa.String(length=50), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fihirana', schema=None) as batch_op:
        batch_op.create_index('idx_fihirana_collection', ['collection'], unique=False)
        batch_op.create_index('idx_fihirana_collection_numero', ['collection', 'numero'], unique=False)
        batch_op.create_index('idx_fihirana_numero', ['numero'], unique=False)
        batch_op.create_index('idx_fihirana_search', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_fihirana_collection'), ['collection'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fihirana', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fihirana_collection'))
        batch_op.drop_index('idx_fihirana_search', postgresql_using='gin')
        batch_op.drop_index('idx_fihirana_numero')
        batch_op.drop_index('idx_fihirana_collection_numero')
        batch_op.drop_index('idx_fihirana_collection')

    op.drop_table('fihirana')
    # ### end Alembic commands ###
