"""Add verse-based Fihirana structure with Sokajy, Hira, Tononkira tables

Revision ID: a9f4f31ffd71
Revises: 447058c615dd
Create Date: 2025-11-18 23:57:23.142787

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a9f4f31ffd71'
down_revision = '447058c615dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fihirana_legacy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('paroles', sa.Text(), nullable=False),
    sa.Column('collection', sa.String(length=50), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fihirana_legacy', schema=None) as batch_op:
        batch_op.create_index('idx_fihirana_legacy_collection', ['collection'], unique=False)
        batch_op.create_index('idx_fihirana_legacy_numero', ['numero'], unique=False)
        batch_op.create_index('idx_fihirana_legacy_search', ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('ix_fihirana_legacy_collection'), ['collection'], unique=False)

    op.create_table('sokajy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anarana', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hira',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sokajy_id', sa.Integer(), nullable=True),
    sa.Column('lohateny', sa.String(length=255), nullable=False),
    sa.Column('isa_andininy', sa.Integer(), nullable=False),
    sa.Column('mpanoratra', sa.String(length=255), nullable=True),
    sa.Column('collection', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['sokajy_id'], ['sokajy.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hira', schema=None) as batch_op:
        batch_op.create_index('idx_hira_collection', ['collection'], unique=False)
        batch_op.create_index('idx_hira_sokajy', ['sokajy_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hira_collection'), ['collection'], unique=False)

    op.create_table('tononkira',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hira_id', sa.Integer(), nullable=False),
    sa.Column('andininy', sa.Integer(), nullable=False),
    sa.Column('tononkira', sa.Text(), nullable=False),
    sa.Column('fiverenany', sa.Boolean(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['hira_id'], ['hira.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tononkira', schema=None) as batch_op:
        batch_op.create_index('idx_tononkira_hira', ['hira_id'], unique=False)
        batch_op.create_index('idx_tononkira_search', ['search_vector'], unique=False, postgresql_using='gin')

    with op.batch_alter_table('fihirana', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_fihirana_collection'))
        batch_op.drop_index(batch_op.f('idx_fihirana_collection_numero'))
        batch_op.drop_index(batch_op.f('idx_fihirana_numero'))
        batch_op.drop_index(batch_op.f('idx_fihirana_search'), postgresql_using='gin')
        batch_op.drop_index(batch_op.f('ix_fihirana_collection'))

    op.drop_table('fihirana')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fihirana',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('numero', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('titre', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('paroles', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('collection', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('fihirana_pkey'))
    )
    with op.batch_alter_table('fihirana', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fihirana_collection'), ['collection'], unique=False)
        batch_op.create_index(batch_op.f('idx_fihirana_search'), ['search_vector'], unique=False, postgresql_using='gin')
        batch_op.create_index(batch_op.f('idx_fihirana_numero'), ['numero'], unique=False)
        batch_op.create_index(batch_op.f('idx_fihirana_collection_numero'), ['collection', 'numero'], unique=False)
        batch_op.create_index(batch_op.f('idx_fihirana_collection'), ['collection'], unique=False)

    with op.batch_alter_table('tononkira', schema=None) as batch_op:
        batch_op.drop_index('idx_tononkira_search', postgresql_using='gin')
        batch_op.drop_index('idx_tononkira_hira')

    op.drop_table('tononkira')
    with op.batch_alter_table('hira', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hira_collection'))
        batch_op.drop_index('idx_hira_sokajy')
        batch_op.drop_index('idx_hira_collection')

    op.drop_table('hira')
    op.drop_table('sokajy')
    with op.batch_alter_table('fihirana_legacy', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fihirana_legacy_collection'))
        batch_op.drop_index('idx_fihirana_legacy_search', postgresql_using='gin')
        batch_op.drop_index('idx_fihirana_legacy_numero')
        batch_op.drop_index('idx_fihirana_legacy_collection')

    op.drop_table('fihirana_legacy')
    # ### end Alembic commands ###
