"""Create Bible tables (Livre, Chapitre, Verset)

Revision ID: e629032f0dc2
Revises: 
Create Date: 2025-11-18 22:19:47.092635

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e629032f0dc2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('livre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('abbrev', sa.String(length=10), nullable=False),
    sa.Column('testament', sa.String(length=2), nullable=False),
    sa.Column('ordre', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('abbrev'),
    sa.UniqueConstraint('nom'),
    sa.UniqueConstraint('testament', 'ordre', name='uq_livre_testament_ordre')
    )
    with op.batch_alter_table('livre', schema=None) as batch_op:
        batch_op.create_index('ix_livre_ordre', ['ordre'], unique=False)
        batch_op.create_index('ix_livre_testament', ['testament'], unique=False)

    op.create_table('chapitre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('livre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['livre_id'], ['livre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('livre_id', 'numero', name='uq_chapitre_livre_numero')
    )
    with op.batch_alter_table('chapitre', schema=None) as batch_op:
        batch_op.create_index('ix_chapitre_livre_id', ['livre_id'], unique=False)

    op.create_table('verset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.Integer(), nullable=False),
    sa.Column('texte', sa.Text(), nullable=False),
    sa.Column('chapitre_id', sa.Integer(), nullable=False),
    sa.Column('texte_search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.ForeignKeyConstraint(['chapitre_id'], ['chapitre.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chapitre_id', 'numero', name='uq_verset_chapitre_numero')
    )
    with op.batch_alter_table('verset', schema=None) as batch_op:
        batch_op.create_index('ix_verset_chapitre_id', ['chapitre_id'], unique=False)
        batch_op.create_index('ix_verset_texte_search', ['texte_search_vector'], unique=False, postgresql_using='gin')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('verset', schema=None) as batch_op:
        batch_op.drop_index('ix_verset_texte_search', postgresql_using='gin')
        batch_op.drop_index('ix_verset_chapitre_id')

    op.drop_table('verset')
    with op.batch_alter_table('chapitre', schema=None) as batch_op:
        batch_op.drop_index('ix_chapitre_livre_id')

    op.drop_table('chapitre')
    with op.batch_alter_table('livre', schema=None) as batch_op:
        batch_op.drop_index('ix_livre_testament')
        batch_op.drop_index('ix_livre_ordre')

    op.drop_table('livre')
    # ### end Alembic commands ###
